language: go
os:
  - linux
  - osx
go:
  - 1.14.x
go_import_path: github.com/bh90210/go-sessions/v3
env:
 global:
   - GO111MODULE=on
install:
  - go get -t ./...
script:
  - go test -v -cover ./...
after_script:
  # examples
  - cd ./_examples
  - go get ./...
  - go test -v -cover ./...
  - cd ../
